### ISSUE TITLE
error-feature request

### ISSUE THREAD

**Issue by SeyedHashtag** [ReturnFI/Hysteria2#12]
سلام و احترام. بنظر در کانفیگ سمت سرور در بخش maxIncomingStreams عدد 60 ناکافی باشه چون بعد از مدتی در v2rayN کانکشن تقریبا قطع میشه و خطای too many streams در لاگ نشان داده میشه. اگر بشه این مقادیر رو از ربات و هم پنل عوض کرد خیلی عالی میشه.
ظمنا تلاش کردم که کانفیگ مشابهی رو در S-UI بسازم ولی بدلیل نامشخصی فقط با کانفیگ پنل شما کار میکنه اگر امکان داره لطفا بگید که چه نکته ای داره.
ضمنا چند تا باگ دیدم:
1-ربات اصلا استارت نشد و البته درسمت سرور هم ننوشته بود که یوزر ادمین بصورت عددی-با @ یا بدونش باشه که من دومورد آخر رو تست کردم ولی کارساز نبود، بات تلگرامی اسکریپ realityezpz هم جالب هست که میشه مشابه اون هم پیاده سازی کرد.
2-ساب سینگ باکس هم لینک نمیده متاسفانه، لطفا اگر امکان داره در بخشی که qrcode میده اون هم اضافه بشه.
 

با تشکر از پروژه ی آموزنده و خوبتون

**Comment by ReturnFI** [comment]
سلام وقتتون بخیر ممنون از پیشنهادتون
در مورد maxIncomingStreams حتما مقادیر بالاتری قرار میدم ممنون از نگاه دقیقی که داشتید.
درمورد پنل s-ui من هنوز فرصت نکردم پنل عیلرضا عزیز❤️ نصب کنم و تست کنم اما تفاوت فقط در هسته هستش.
علیرضا عزیز از هسته sing-box استفاده کردن و من از هسته hysteria2 بطور کلی شاید در obfs یا مقادیر دیگه تفاوت جزئی باشه ولی نباید مشکلی باشه.

1.ربات تلگرام رو باید با آیدی عددی تنها بدون هیچ کارکتری استارت کنید
میتونید آیدی عددی خودتون رو از ربات های مختلفی مثل @userinfobot دریافت کنید.

2.ساب لینک sing-box فعلا فقط در ربات و درصورتی که فعال کرده باشید به شما لینک میده.


و در انتها ممنون از لطفی که دارید پنل هنوز به نسخه 1 نرسیده و احتمالا تغییرات زیادی اتفاق بیفته.
سربلند باشید.
