### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by SeyedHashtag** [ReturnFI/Hysteria2#15]
درود. لطفا برای سرورهایی که چندتا آی پی دارند، قابلیت تعیینشون یاتغییرشون یا امکان استفاده ی همزمان رو قرار بدین.

**Comment by ReturnFI** [comment]
درود وقتتون بخیر.
امکان تغییر IP اضافه شد از منو Advance و گزینه 11 میتویند IP های کانفیگ خودتون تغییر بدید.
ممنون از پیشنهاد خوبتون و عذرخواهی اگر دیر شد.

**Comment by SeyedHashtag** [comment]
درود برشما و تشکر از وقتی که گذاشتید.
