### ISSUE TITLE
Error cli.py

### ISSUE THREAD

**Issue by Atn71** [ReturnFI/Hysteria2#20]
سلام و درود 
بعد نصب و موقع اینستال این ارور گرفتم و نتوانستم حل کنم
Traceback (most recent call last):
  File "/etc/hysteria/core/cli.py", line 43, in <module>
    def run_cmd(command: list[str]):
TypeError: 'type' object is not subscriptable

ممنون میشم راهنمایی کنید
سپاسگزارم

**Comment by ReturnFI** [comment]
سلام. وقتتون بخیر
سیستم عامل سرورتون اوبونتو یا دبین انتخاب کنید.

**Comment by Atn71** [comment]
اوبونتو ۲۰

**Comment by ReturnFI** [comment]
میتونید فعلا ورژن پایتون باید آپدیت کنید
یا اوبونتو 22 انتخاب کنید.
تا در آپدیت بعدی رفعش کنم.

ممنون از گزارش باگ❤
