### ISSUE TITLE
Error : core/cli.py", line 44, in <module>

### ISSUE THREAD

**Issue by NoRRt** [ReturnFI/Hysteria2#23]
salam khaste nabashid - man ba in error movajehe misham :

![Untitled](https://github.com/user-attachments/assets/2e411814-fc50-44a2-9188-5eeda314e86e)

raceback (most recent call last):
  File "/etc/hysteria/core/cli.py", line 44, in <module>
    def run_cmd(command: list[str]):
TypeError: 'type' object is not subscriptable

**Comment by ReturnFI** [comment]
سلام وقتتون بخیر
ورژن اوبنتو 22 به بالا یا دبین 11 به بالا انتخاب کنید.

**Comment by NoRRt** [comment]
تست کردم با دبین 11  بازم همین مشکل  رو داشت

**Comment by NoRRt** [comment]
این تست رو با ubuntu-22.04 بود که مشکل داشت

**Comment by ReturnFI** [comment]
> این تست رو با ubuntu-22.04 بود که مشکل داشت

چون از virtual environments استفاده میکنیم شاید به مشکل خوردید.
یکبار از سرور خارج بشید (دیسکانکت) کنید و دوباره SSH بزنید 
با دستور `hys2` اسکریپت ران کنید

**Comment by NoRRt** [comment]
> > این تست رو با ubuntu-22.04 بود که مشکل داشت
> 
> چون از virtual environments استفاده میکنیم شاید به مشکل خوردید. یکبار از سرور خارج بشید (دیسکانکت) کنید و دوباره SSH بزنید با دستور `hys2` اسکریپت ران کنید

از این طریق درست شده
