### ISSUE TITLE
change SNI

### ISSUE THREAD

**Issue by mywork401** [ReturnFI/Hysteria2#25]
باسلام و تشکر از زحمات شما
آیا امکان تغییر sni وجود دارد ؟؟

**Comment by ReturnFI** [comment]
سلام وقتتون بخیر ممنون لطف دارین❤️🙏🏻
در حال حاضر خیر چون cert هارو با همین bts.com میگیریم
ولی حتما در ورژن های بعدی اعمال میکنم
ممنون نظرتون❤️

**Comment by Atn71** [comment]
سلام مهندس 
میشود خودمون cert دامین خودمون بگیریم و جای ادرس و sni بدیم و در config.jason ادیت کنیم تا اعمال شود
در ضمن اگر بشه بصورت زیرباشه
روی بعضی VPs چک کردم به این صورت و بدون sni  بهتر عمل میکند
hy2://pass1@ip:port?obfs=salamander&obfs-password=pass2
مثال
hy2://4294035691ef1086@dl2.ildeco.ir:443/?obfs=salamander&obfs-password=74e4b35d#test

ولی نمی دونم چه تغییرات بدم که به صورت مثال بالا دربیاید 
سپاسگزارم
