### ISSUE TITLE
some users blocked!

### ISSUE THREAD

**Issue by babaksc** [ReturnFI/Hysteria2#30]
باسلام خدمت شما دوست هنرمند
ممنون از زحمات و تلاش و همچنین نتیجه جذاب و عالی شما 
دونکته عرض می کنم :
یکی اینکه یوزر اول گاها بدون دلیل بلاک میشود. تا امروز در یک هفته حدود 6 بار متوجه شدم که بلاک شده
دوم اینکه sni استفاده شده در اینترنت ایرانسل ضعیف عمل میکند که با پنل دیگری که از اسن ان آی گوگل دات کام استفاده میکرده تست کردم این مشکل وجود نداشت 

صرفا جهت اطلاع عرض کردم شاید مفید باشد 
بازم ممنون و یک دنیا سپاس

**Comment by ReturnFI** [comment]
سلام وقتتون بخیر
ممنون لطف دارین 

در مورد یوزر اول بله درسته این مشکل رو چندبار دیدم
قبلا باگی در خود هسته هیستریا۲ بود که یوزر با کارکترهای بزرگ بطور مثال : Happy رو قبول نمیکرد و باید تمام کارکترها کوچیک میبود.
یکبار چک کردم این مورد رفع شده بود و این محدودیت از داخل اسکریپت برداشتم که یوزر با کارکتر بزرگ هم قبول کنه اما مثل اینکه هنوز مشکل وجود داره
یک بررسی بکنید ببینید یوزرتون کارکتر بزرگ داره یا خیر

در مورد sni هم حتما در اسرع وقت اضافه میکنم تا sni رو هم بشه تغییر داد

ممنون از همکاری تون کمک میکنید به پروژه🙏🏻❤️

**Comment by babaksc** [comment]
ممنون از توجهتون 
الان که دقت کردم احتمالا فقط و فقط یوزر اول بلاک میشه یعنی اولین یوزری که ساختم و بقیه نه ، و اینکه نه هیچ حرف بزرگی استفاده نمیکنم بوزری که بلاک میشه b1 بود 
پس منتظر اپدیت های بعدی هستم 🙏❤️
در تغییرات نسخه آخر نوشتین بک آپ ، شاید من بد متوجه شدم الان میشه بک اپ گرفت از کاربرها، یا نه هنوز 
بازم مرسی 🙏

**Comment by ReturnFI** [comment]
خواهش میکنم ❤️
حتما چک میکنم اما احتمال میدم باگ خود هیستریا۲ باشه بازم یوزر بدون عدد وارد کنید و تست کنید
بله میشه از طریق ربات تلگرام از بخش های مهم که فایل های سرتیفیکت , config.json و users.json بکاپ گرفت،
یوزر ها هم شامل بکاپ میشن.
کافیه بعد از بروزرسانی پنل، ربات رو از تلگرام دوباره استارت کنید تا منو بکاپ براش بیاد.

ممنون از همکاریتون❤️

**Comment by ReturnFI** [comment]
سلام.
امروز حتما بررسی میکنم 
ورژن هسته هستریا که دارید رو میتونید بهم بگید؟

**Comment by meysamrn** [comment]
> سلام. امروز حتما بررسی میکنم ورژن هسته هستریا که دارید رو میتونید بهم بگید؟

نمیدونم ، ولی من همین آخرین نسخه پنل و همینطور هسته هیستریا 2 رو به روزرسانی کردم که فکر کنم نسخه 2.5.1 باشه

**Comment by ReturnFI** [comment]
> > سلام. امروز حتما بررسی میکنم ورژن هسته هستریا که دارید رو میتونید بهم بگید؟
> 
> نمیدونم ، ولی من همین آخرین نسخه پنل و همینطور هسته هیستریا 2 رو به روزرسانی کردم که فکر کنم نسخه 2.5.1 باشه

سلام. یکسری ایرادات داشت رفع کردم.
بازم چک کنید ولی دیگه مشکلی نباید باشه.

ممنون از همکاریتون ❤
@babaksc 
@meysamrn
