### ISSUE TITLE
provide mihomo config

### ISSUE THREAD

**Issue by dnvcupid** [ReturnFI/Hysteria2#35]
provide mihomo config

**Comment by ReturnFI** [comment]
What's mihomo?

**Comment by ReturnFI** [comment]
> https://github.com/MetaCubeX/mihomo

> A simple Python Pydantic model for Honkai: Star Rail parsed data from the Mihomo API.

This is a API for video game(Honkai: Star Rail)

**Comment by ReturnFI** [comment]
> https://github.com/MetaCubeX/mihomo/tree/Meta
I'm not familiar with mihomo if you can make PR
