### ISSUE TITLE
Obfuscation!!

### ISSUE THREAD

**Issue by harryngne** [ReturnFI/Hysteria2#39]
Can i use hysteria2 without obfuscation ? , i mean it can turn off obfuscation ?

**Comment by ReturnFI** [comment]
> By default, the Hysteria protocol mimics HTTP/3. If your network specifically blocks QUIC or HTTP/3 traffic (but not UDP in general), obfuscation can be used to work around this. We currently have an obfuscation implementation called "Salamander" that converts packets into seamingly random bytes with no pattern. This feature requires a password that must be identical on both the client and server sides.


The ability to disable this feature is not currently supported within my script.
However, I will definitely review and add it in future versions.

**Comment by ReturnFI** [comment]
> Can i use hysteria2 without obfuscation ? , i mean it can turn off obfuscation ?

Hi,
I've added the obfs management feature to the dev branch. Please test it and let me know if there are any issues before I release it.

Dev branch install command:
```
bash <(curl https://raw.githubusercontent.com/ReturnFI/Hysteria2/Dev/install.sh)
```

**Comment by harryngne** [comment]
> > Can i use hysteria2 without obfuscation ? , i mean it can turn off obfuscation ?
> 
> 
> 
> Hi,
> 
> I've added the obfs management feature to the dev branch. Please test it and let me know if there are any issues before I release it.
> 
> 
> 
> The feature has been added to the **Advance menu**.
> 
> 
> 
> Dev branch install command:
> 
> ```
> 
> bash <(curl https://raw.githubusercontent.com/ReturnFI/Hysteria2/Dev/install.sh)
> 
> ```

thanks for adding it, i will try it, you know because Surge5 app doesn't have obfuscation 😅
