### ISSUE TITLE
موضوع tor

### ISSUE THREAD

**Issue by meysamrn** [ReturnFI/Hysteria2#42]
پیشنهاد میکنم از پروژه تور هم در پروژه استفاده بشه ، الان در بعضی از اپراتورها و ... وارپ بعضا با اختلال و مشکلات ترافیک داده مواجه می شه که اگه بتونید از بعضی از پروژه ها استفاده بکنید برای داخلی سازی این قابلیت یا حداقل قابلیت ارتباط outbound از طریق socks رو اضافه کنید که ما بتونیم با استفاده از اسکریپتهایی مانند : https://github.com/FDX100/Auto_Tor_IP_changer یا https://github.com/sinasims/torsina بتونیم توی پروت مخصوصی ارتباط ساکس رو لایه آخر تغییر آی پی به جای وارپ بزاریم

**Comment by ReturnFI** [comment]
سلام وقتتون بخیر
ایده بسیار خوبیه چون هیستریا از socks پشتیبانی میکنه و اولین مدل وارپی که اجرا کردم رو پروژه با socks بود
اما خود tor هنوز نمیدونم چقدر قانونی و در کدوم دیتاسنتر ها مجاز هستش؟
نمیخوام برای کاربران عزیزی مثل شما خدایی نکرده از سمت دیتاسنتر اخطاری بیاد و یا اکانتتون بن بشه
