### ISSUE TITLE
Why do we need to escape colons between username and password in URLs?

### ISSUE THREAD

**Issue by jack4pear** [ReturnFI/Hysteria2#43]
When converting to clash, it is necessary to manually change them back to colons.

**Comment by ReturnFI** [comment]
Hi there,
We use this method to authenticate users with the server.
In some applications, the colon character itself was not responsive, so we had to use URL-encoding the colon as %3A.

**Comment by jack4pear** [comment]
What applications? I have tried v2rayn and NekoBox, both of which do not require escaping. Perhaps it is possible to list non escaped and escaped URLs, and indicate which applications need to use escaped URLs.

**Comment by jack4pear** [comment]
I tried Hiddify, v2rayN, and NoreBox on my Android device, and both escaped and non-escaped URLs work without issues. 
Never mind.  When converting it to other configurations, I manually replace the colons.  Thx.
