### ISSUE TITLE
Ban Iranian websites 

### ISSUE THREAD

**Issue by aminjoharinia** [ReturnFI/Hysteria2#45]
Hi
I love Your Project, Thanks for your efforts
is there any solution to block Iranian websites like x-ray core asset geo files or maybe a better solution?

**Comment by ReturnFI** [comment]
Hi Amin, and thank you for your kindness.❤

As our default configuration, we use the geo files from the Chocolate4U project, and they block websites and IP addresses from Iran.
You can see this in the config.json file,[ line 68](https://github.com/ReturnFI/Hysteria2/blob/bb85f9be4301c619aa632499455b777ea077bc70/config.json#L68), under the `acl` section.

If you add warp through the menu, you can go into warp settings and route the traffic for those blocked sites and IP addresses through warp.

Here's the link to the Hysteria2 documentation:
https://v2.hysteria.network/docs/advanced/ACL/
