### ISSUE TITLE
Activation Error

### ISSUE THREAD

**Issue by santraxDE** [ReturnFI/Hysteria2#46]
![image](https://github.com/user-attachments/assets/3b0aa61e-3a09-4801-ac85-a34cb7b4d393)

Hi ;)
when trying to run the script i get the following error on a free Orcale server. Is there any port that i must clear for it to work? 
best regards

**Comment by ReturnFI** [comment]
Hi,
You can check the Hysteria2 service logs and send them for better troubleshooting using the following commands:
``` bash
journalctl -u hysteria-server.service
```
or
``` bash
systemctl status hysteria-server.service
```

Thanks!
