### ISSUE TITLE
certificate

### ISSUE THREAD

**Issue by mahmoodhabibi333** [ReturnFI/Hysteria2#48]
درود روش گرفتن certificate رو در پنل پیدا نمیکنم لطفا اگر امکان داره راهنمایی کنید ممنونم

**Comment by ReturnFI** [comment]
درود به شما
از ابزار OpenSSL برای تولید گواهی (self-signed certificate) استفاده میکنیم.
میتونید در فایل core/scripts/hysteria2/install.sh لاین [15](https://github.com/ReturnFI/Hysteria2/blob/0fbc8d3bde0a7274070f2639fcdd0b3be3df36e5/core/scripts/hysteria2/install.sh#L15) مشاهده کنید.
