### ISSUE TITLE
درخواست قابلیت اپلود فایل بکاپ در بات

### ISSUE THREAD

**Issue by SeyedHashtag** [ReturnFI/Hysteria2#51]
درحال حاضر بات قابلیت ارسال بکاپ رو داره ولی قابلیت دریافت و اعمال بکاپ رو نداره. البته قابلیت snapshot هم میتونه جالب باشه.
مثلا هر روز یا هرهفته بصورت خودکار بکاپ ذخیره بشه و تا یه مدتی سیو باشه تا امکان بازگشت به تنظیمات قبل وجود داشته باشه. باتوجه به اینکه یکبار به شکل ناگهانی پنل تمام اطلاعات یوزر ها رو پاک کرد.

**Comment by ShadowOwlCode** [comment]
سلام.
چون بکاپ من نوشتم گفتم دقیق بپرسم میخوای از سمت بات بکاپ برگردونی؟
یه کرونجاب هم داره پروژه خودکار بکاپ هر 6 ساعت داخل فولدر `opt/hysbackup/` میگیره

**Comment by SeyedHashtag** [comment]
سلام. ممنون که اشاره کردید. بله از طریق بات

**Comment by ReturnFI** [comment]
سلام.
ربات رو باید بازنویسی بشه و اصطلاحا ریفکتور بشه.
یکم زمان بره ولی حتما انجامش میدم 
اما برای بازگردانی بکاپ اینکار از سمت ربات انجام نشه بهتره
تلاش کردم برای پنل یک نسخه وب بنویسم اما خب فرانتکار نیاز داریم😁
