### ISSUE TITLE
باگ در بخش certificate

### ISSUE THREAD

**Issue by SeyedHashtag** [ReturnFI/Hysteria2#52]
سلام و درود.
درحال حاظر اگر یک certificate رو برای ساب ثبت کنید و بعد از گزینه ی غیر فعال کردنش استفاده کنید و دوباره بخواید فعالش کنید/تغییری ایجاد کنید- پنل این اجازه رو نمیده. احتمالا حتی اگر اطلاعات رو اشتباهی هم بزنید به مشکل مشابهی برخورد خواهید کرد.

**Comment by ReturnFI** [comment]
سلام وقتتون بخیر.
میتونید دقیق تر توضیح بدید که بعد از غیرفعال سازی و دوباره فعال سازی چه اتفاقی میفته تا بررسی کنم یا اسکرین شات بفرستید.
ممنون که کمک میکندی به بهبود پروژه❤

**Comment by ReturnFI** [comment]
بعد از stop کردن سرویس های ساب لینک 
به صورت خودکار certificate هم پاک میشه تا مشکلی در دوباره فعال سازی نداشته باشید.
