### ISSUE TITLE
درخواست بهبود در بخش نمایش اطلاعات یوزرها

### ISSUE THREAD

**Issue by SeyedHashtag** [ReturnFI/Hysteria2#53]
سلام و تشکر از شما بابت پروژه ی عالیتون.
درحال حاضر در پنل و احتمالا بات، اطلاعات یوزرها رو به دوبخش تقسیم شده.
برای مثال میزان حجم یوزر میتونه به این شکل نمایش داده بشه 14/100GB
یا مثلا روز های باقی مونده به شکل 17/30 days

**Comment by ReturnFI** [comment]
سلام لطف دارید.
اگر طراحی که بنظرتون زیباترش میکنه بتونید بصورت یه عکس بفرستید بهتره تا اجرایش کنم.
