### ISSUE TITLE
پلی نشدن ویدیوها در یوتیوب

### ISSUE THREAD

**Issue by ssffss2204** [ReturnFI/Hysteria2#56]
با تشکر از شما بابت پروژه بسیار عالیتون
مشکلی ک من دارم ویدیوهای یوتیوب برام فقط 30 یا 40 ثانیه اولشون پلی میشه و بقیش پلی نمیشه با چند ..ترشکن دیگه امتحان کردم بدون مشکل پلی میشن

**Comment by ReturnFI** [comment]
سلام خواهش میکنم لطف دارین.❤️
ممکنه ایراد از برنامه ای باشه که استفاده میکنید
اپ هیدیفای تست کنید ببینید بازم مشکل دارین یا خیر

از سمت سرور هم دو مورد رو تست کنید یکی sni تغییر بدید که از منو گزینه Advance Menu و change sni 
مورد دوم استفاده از وارپ که داخل منو Advance Menu هستش میتونید نصب کنید و تنظیم کنید

**Comment by ssffss2204** [comment]
از هیدیفای استفاده میکنم
از چه sni هایی میشه استفاده کرد؟
تشکر

**Comment by ReturnFI** [comment]
> از هیدیفای استفاده میکنم از چه sni هایی میشه استفاده کرد؟ تشکر

هر sni که مدنظرتون
خودم از دیفالت پنل استفاده میکنم و شاید نزدیک ۷ ماه هستش که روی سرویس های مختلف تستش کردم
از nekobox هم تست بگیرید
