### ISSUE TITLE
Sing-Box Sub Link

### ISSUE THREAD

**Issue by abdolgasl** [ReturnFI/Hysteria2#57]
اول ممنون بابت اسکریپت.
خروجی گزینهٔ Sing-Box Sublink دقیقا کجاست؟ فعال کردم ولی جایی بین آپشن‌های منوها نمی‌بینم که subscription link نمایش بده.

**Comment by ReturnFI** [comment]
> اول ممنون بابت اسکریپت. خروجی گزینهٔ Sing-Box Sublink دقیقا کجاست؟ فعال کردم ولی جایی بین آپشن‌های منوها نمی‌بینم که subscription link نمایش بده.

سلام ممنون از لطفتون ❤️
لینک ساب سینگباکس و نرمال فعلا داخل ربات تلگرام نمایش داده میشه ولی حتما به منو shell اضافه میکنم

**Comment by ReturnFI** [comment]
اضافه شده به منو و گزینه [9] ↝ Show User URI
