### ISSUE TITLE
درخواست لیست یوزرها

### ISSUE THREAD

**Issue by babaksc** [ReturnFI/Hysteria2#60]
با سلام و با تشکر بابت زحمات شما 
همه چیز خوب و عالیه 
در خواستی داشتم اگر میشد لیست اسامی کاربران را در ربات دید و بجای تایپ نام کاربری هر کاربر اسمش را از لیست انتخاب کرد خیلی عالی میشه، چون بخاطر سپردن نام کاربران واقعا سخته ;)
بازم ممنونم

**Comment by ReturnFI** [comment]
سلام وقتتون بخیر شادی.
لطف دارید❤️.

برای سرچ کاربر در ربات تلگرام کافیه ربات botfather باز کنید کامند `mybots/` بزنید ربات مورد نظرتون انتخاب کنید 
بعد روی دکمه `Bot Settings` بزنید در منوی جدید دکمه `Inline Mode` انتخاب کنید و در نهایت Turn On کنید این فیچر رو

بعد از روشن کردن Inline Mode کافیه داخل ربات خودتون بشید و آیدی ربات رو وارد کنید بطور مثال

`@myHysteria2`

بعد از این لیست کاربران براتون میاد در صورتی هم که خواستید اسم خاصی رو سرچ کنید میتونید دوباره آیدی ربات خودتون داخل ربات تایپ کنید یه فاصله بزارید و اسم رو سرچ کنید
مثال

`@myHysteria2 test`

سربلند باشید❤️

**Comment by babaksc** [comment]
خیلی هم عالی 
ممنون بابت توضیحات❤️
موفق باشید ❤️
